# Generated by Django 5.2.4 on 2025-07-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_text', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('image_embedding', models.CharField(blank=True, max_length=200, null=True)),
                ('image_tags', models.CharField(max_length=100)),
            ],
        ),
    ]
