# Generated by Django 5.2.4 on 2025-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_imagedata_created_at_imagedata_image_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='imagedata',
            name='image_meta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='image_tags',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='image_tags',
            field=models.ManyToManyField(related_name='image_tag', to='search.tags'),
        ),
    ]
