# Generated by Django 5.2.4 on 2025-07-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_tags_imagedata_image_meta_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
