# Generated by Django 5.2.4 on 2025-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(upload_to='image_data/'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='image_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='image_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='image_tags',
            field=models.ManyToManyField(related_name='images', to='search.tag'),
        ),
    ]
