# Generated by Django 5.2.4 on 2025-07-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_imagedata_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
